// <auto-generated />
using System;
using GenericFanSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericFanSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241120011938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GenericFanSite.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GenericFanSite.Models.ForumPost", b =>
                {
                    b.Property<int>("ForumPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ForumDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForumDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ForumText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ForumTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ForumUserAppUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ForumYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ForumPostId");

                    b.HasIndex("ForumUserAppUserId");

                    b.ToTable("ForumPosts");
                });

            modelBuilder.Entity("GenericFanSite.Models.ForumPost", b =>
                {
                    b.HasOne("GenericFanSite.Models.AppUser", "ForumUser")
                        .WithMany()
                        .HasForeignKey("ForumUserAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumUser");
                });
#pragma warning restore 612, 618
        }
    }
}
